services:
    db:
      image: postgres:16
      environment:
        POSTGRES_DB: release_assistant
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Pranathi25
      ports: [ "5000:5000" ]
      volumes: [ pgdata:/var/lib/postgresql/data ]
  volumes:
    pgdata: