spring.application.name=ReleaseAssistant_backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://localhost:5000/release_assistant
spring.datasource.username=postgres
spring.datasource.password=Pranathi25
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

ai.api.url=https://api.openai.com/v1/chat/completions
ai.api.key=${AI_API_KEY:}
ai.model=gpt-4o-mini